### ISSUE TITLE
Can't retire a service. should be able to mark it as retired.

### ISSUE THREAD

**Issue by watucker** [cedadev/ceda-services-portal#30]

**Comment by watucker** [comment]
To check with Sam what the requirements are.

**Comment by amanning9** [comment]
CEDA Requirements:
* Should not be able to register for it anymore. (This is most important). Tell them this is gone.
* Exipre everyone who had that group. (nice to have).
* Definitly shouldn't ask people to reapply for thing that doesn't have impact anymore.

**Comment by amanning9** [comment]
Clarification: When you retire a service all the users' grants should be revoked.
